#!/usr/bin/env python3
"""Regenerates every file under ``contracts/schemas/v<N>/`` from the
Pydantic models in ``src/multicloud_network_mcp/contracts/models/``.

Models are this contract's canonical source of truth (see
``docs/architecture.md``'s "why schemas are generated from models, not
hand-authored" section) -- this script is the one place that
relationship is made concrete and reproducible. Every generated file
carries a top-level ``$comment`` marking it as generated, so a reader
opening the file directly (not through this script) still knows not to
hand-edit it.

Usage (from the package root)::

    python scripts/generate_schemas.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))

from multicloud_network_mcp.contracts.models import (  # noqa: E402
    Address,
    Attachment,
    CollectionWarning,
    DnsResolver,
    DnsRule,
    DnsZone,
    Endpoint,
    Finding,
    FirewallRule,
    Gateway,
    Interconnect,
    InterconnectAttachment,
    LoadBalancer,
    Network,
    NetworkInterface,
    ObservabilityReference,
    PathExplanation,
    Peering,
    ProviderCapabilityManifest,
    ResponseEnvelope,
    Route,
    RouteTable,
    Subnet,
    TopologyGraph,
    TransitHub,
    VpnGateway,
    VpnTunnel,
)
from multicloud_network_mcp.contracts.version import (  # noqa: E402
    CONTRACT_VERSION,
    SCHEMA_BASE_URI,
    SCHEMA_ID_VERSION,
)

_OUT_DIR = (
    _REPO_ROOT
    / "src"
    / "multicloud_network_mcp"
    / "contracts"
    / "schemas"
    / f"v{SCHEMA_ID_VERSION}"
)

# One entry per schema file: (file stem, model class). File stems are
# kebab-case to match this contract's own resource-type slug style.
_MODELS: list[tuple[str, type]] = [
    # Resources
    ("network", Network),
    ("subnet", Subnet),
    ("network-interface", NetworkInterface),
    ("address", Address),
    ("route-table", RouteTable),
    ("route", Route),
    ("firewall-rule", FirewallRule),
    ("gateway", Gateway),
    ("transit-hub", TransitHub),
    ("attachment", Attachment),
    ("peering", Peering),
    ("vpn-gateway", VpnGateway),
    ("vpn-tunnel", VpnTunnel),
    ("interconnect", Interconnect),
    ("interconnect-attachment", InterconnectAttachment),
    ("dns-zone", DnsZone),
    ("dns-resolver", DnsResolver),
    ("dns-rule", DnsRule),
    ("load-balancer", LoadBalancer),
    ("endpoint", Endpoint),
    ("observability-reference", ObservabilityReference),
    # Topology
    ("topology-graph", TopologyGraph),
    # Diagnostics
    ("finding", Finding),
    ("path-explanation", PathExplanation),
    # Envelope
    ("response-envelope", ResponseEnvelope),
    ("collection-warning", CollectionWarning),
    # Capability
    ("provider-capability-manifest", ProviderCapabilityManifest),
]


def _generate_one(stem: str, model: type) -> dict:
    schema = model.model_json_schema()
    ordered: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{SCHEMA_BASE_URI}/schemas/v{SCHEMA_ID_VERSION}/{stem}.schema.json",
        "$comment": (
            f"GENERATED -- do not hand-edit. Produced by scripts/generate_schemas.py "
            f"from multicloud_network_mcp.contracts.models.{model.__name__} "
            f"(contract version {CONTRACT_VERSION}). Edit the Pydantic model and "
            f"re-run the script instead."
        ),
    }
    ordered.update(schema)
    return ordered


def main() -> None:
    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for stem, model in _MODELS:
        schema = _generate_one(stem, model)
        out_path = _OUT_DIR / f"{stem}.schema.json"
        out_path.write_text(json.dumps(schema, indent=2, sort_keys=False) + "\n")
        written.append(out_path.relative_to(_REPO_ROOT))

    stale = {
        p
        for p in _OUT_DIR.glob("*.schema.json")
        if p.name != "index.json" and p.relative_to(_REPO_ROOT) not in written
    }
    for path in stale:
        print(f"warning: stale schema file no longer generated by any model: {path}")

    index = {
        "$comment": "GENERATED -- do not hand-edit. Maps resource/model name to schema file.",
        "contract_version": CONTRACT_VERSION,
        "schemas": {stem: f"{stem}.schema.json" for stem, _ in _MODELS},
    }
    (_OUT_DIR / "index.json").write_text(json.dumps(index, indent=2) + "\n")

    print(f"Wrote {len(written)} schema files + index.json to {_OUT_DIR.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    main()
